[package]

name = "rust_tessel"
version = "0.0.1"
authors = [
	"Kenneth Nierenhausen <kennethnierenhausen@gmail.com>",
	"Chris Lewis <cflewis@google.com>"
]

[[bin]]
name = "main"
doc = false

[dependencies]
unix_socket = "0.5.0"
